const botonNumeros = document.getElementsByClassName("numero")
const botonOperadores = document.getElementsByClassName("operador")
const mostrarValorActual = document.getElementById("valorActual")
const mostrarValorAnterior = document.getElementById("valorAnterior")
const botonBorrar = document.getElementById("borrar")
const botonBorrarTodo = document.getElementById("borrarTodo")
const botonIgual = document.getElementById("igual")
